apiVersion: v1
kind: Service
metadata:
  name: aoai-benchmark
  namespace: aoai-benchmark
  labels:
    app.kubernetes.io/name: aoai-benchmark
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aoai-benchmark
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
